version: '3'
services:
  database:
    build:
      context: ./database
    ports:
      - 3306:3306
    environment:
      MYSQL_HOST: database
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: urgentnews

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
    command: gunicorn app:app -b 0.0.0.0:5000
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    ports:
      - 80:80
    environment:
      - BACKEND_URL=http://backend:5000




      
